version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ${HOME}/storage/postgresql:/var/lib/postgresql/data
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=docker
         - POSTGRES_USER=postgres
    restart: unless-stopped 
  gymapp:
      build: 
        context: .
        dockerfile: Dockerfile-spring
      ports:
      - 8080:8080
      restart: unless-stopped
      depends_on:
        - postgres
      links:
        - postgres
